{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "W6xC-DwcrJMo"
      },
      "outputs": [],
      "source": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "Q1. Explain why we have to use the Exception class while creating a Custom Exception."
      ],
      "metadata": {
        "id": "dQhAVHFwrnWT"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "Ans1. In Python, the Exception class is the base class for all exceptions. This means that when we create a custom exception, we are essentially creating a new subclass of the Exception class.\n",
        "\n",
        "By creating a new subclass of the Exception class, we are able to take advantage of the built-in functionality that is already defined for handling exceptions in Python. This includes the ability to catch exceptions with a try/except block, raising exceptions with the raise statement, and printing informative error messages to the console.\n",
        "\n",
        "Additionally, by subclassing the Exception class, we are able to define our own error messages and attributes for our custom exception. This can be helpful in providing more detailed information about the specific error that occurred, which can make it easier to debug the code."
      ],
      "metadata": {
        "id": "c7D0F6RxsLLR"
      }
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "VJWgX7nitC97"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "Q2. Write a python program to print Python Exception Hierarchy.\n",
        "\n",
        "Ans2. In Python, all exceptions are represented as classes that inherit from the base Exception class. This creates a hierarchy of exceptions, where more specific exceptions inherit from more general ones. Here is a Python program that prints the exception hierarchy using the mro() method"
      ],
      "metadata": {
        "id": "uyAj7SnssgNj"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "def print_exception_hierarchy():\n",
        "    for exc in Exception.__subclasses__():\n",
        "        print(exc.__name__)\n",
        "        for subexc in exc.mro()[1:]:\n",
        "            print(\"  \", subexc.__name__)\n",
        "\n",
        "print_exception_hierarchy()\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "E2rsakqQrpzN",
        "outputId": "61068dc9-e618-434e-9d4e-2820cc0deb71"
      },
      "execution_count": 1,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "TypeError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "StopAsyncIteration\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "StopIteration\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ImportError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "OSError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "EOFError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "RuntimeError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "NameError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "AttributeError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "SyntaxError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "LookupError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ValueError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "AssertionError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ArithmeticError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "SystemError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ReferenceError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "MemoryError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "BufferError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "Warning\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "_OptionError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "error\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "Verbose\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "Error\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "_Error\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "SubprocessError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "Error\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "TokenError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "StopTokenizing\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "error\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "LZMAError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "RegistryError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "_GiveupOnFastCopy\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "EndOfBlock\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "TraitError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "_GiveupOnSendfile\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "error\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "PickleError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "_Stop\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "Empty\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "Full\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ArgumentError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ArgumentTypeError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ConfigError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ConfigurableError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ApplicationError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ErrorDuringImport\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "BdbQuit\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "Restart\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ExceptionPexpect\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "error\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "PtyProcessError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "FindCmdError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "HomeDirError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ProfileDirError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "IPythonCoreError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "InputRejected\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "GetoptError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "Incomplete\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "OptionError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ErrorToken\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "Error\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "TimeoutError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "InvalidStateError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "LimitOverrunError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "QueueEmpty\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "QueueFull\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "PrefilterError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "AliasError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "Error\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "Warning\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "SpaceInInput\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "TaskLocalNotSetError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "InvalidStateError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "Return\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "NoRunningApplicationError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ValidationError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "EditReadOnlyBuffer\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "_Retry\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "DOMException\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "InvalidLayoutError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "HeightIsUnknownError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "MessageError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "Error\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "HTTPException\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "InteractivelyDefined\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "KillEmbedded\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ArgumentError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ZMQBaseError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "NoIPAddresses\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "Error\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "InvalidPortNumber\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "DuplicateKernelError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "error\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ReturnValueIgnoredError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "KeyReuseError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "UnknownKeyError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "LeakedCallbackError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "BadYieldError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ReturnValueIgnoredError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "Return\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "QueueEmpty\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "QueueFull\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "Error\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "WidgetException\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "JsException\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "FormattedTracebackError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "Error\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "_Ipv6UnsupportedError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "HttpLib2Error\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "LapackError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "LinAlgError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ConverterError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "MAError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ParseBaseException\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "RecursiveGrammarException\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "DuplicateConstraint\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "UnsatisfiableConstraint\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "UnknownConstraint\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "DuplicateEditVariable\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "UnknownEditVariable\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "BadRequiredStrength\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "NonGuiException\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "Error\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "InvalidIndexError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "TerminateTrajectory\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "DecompressionBombError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "FFIError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "CDefError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "VerificationError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "VerificationMissing\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "PkgConfigError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "NoFreePortFoundError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ExpatError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "Error\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "BadZipFile\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "LargeZipFile\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ParseBaseException\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "RecursiveGrammarException\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "ResolutionError\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n",
            "UnableToResolveVariableException\n",
            "   Exception\n",
            "   BaseException\n",
            "   object\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "nEF1blfltAcr"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
        "\n",
        "Ans3. The ArithmeticError is a base class for all errors that occur during arithmetic calculations. It is a subclass of the Exception class, and therefore, it is a superclass for more specific error classes.\n",
        "\n",
        "Here are two examples of errors that are defined in the ArithmeticError class:\n",
        "\n",
        "ZeroDivisionError: This error occurs when you try to divide a number by zero. It is a subclass of the ArithmeticError class.\n",
        "\n",
        "OverflowError: This error occurs when a calculation produces a result that is too large to be represented by the available memory or storage space. It is a subclass of the ArithmeticError class\n",
        "\n"
      ],
      "metadata": {
        "id": "32elYrcBtNWX"
      }
    },
    {
      "cell_type": "code",
      "source": [
        " # Here is an example of code that generates a ZeroDivisionError:\n",
        "a = 10\n",
        "b = 0\n",
        "c = a / b   # This will raise a ZeroDivisionError\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 200
        },
        "id": "9e1xJwd3uU2x",
        "outputId": "a4ce05e9-5218-4aca-b399-e39071c89ec5"
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "error",
          "ename": "ZeroDivisionError",
          "evalue": "ignored",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
            "\u001b[0;32m<ipython-input-2-03a60d7bcd6f>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0ma\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m10\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0mb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m \u001b[0mc\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0ma\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0mb\u001b[0m   \u001b[0;31m# This will raise a ZeroDivisionError\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
            "\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Here is an example of code that generates an OverflowError:\n",
        "import math\n",
        "x = math.factorial(1000)  # This will raise an OverflowError\n",
        "\n"
      ],
      "metadata": {
        "id": "kOyQUloSufhr"
      },
      "execution_count": 3,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [],
      "metadata": {
        "id": "JuuDmGxguqEe"
      }
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "GwZLoq3Eukw4"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
        "\n",
        "Ans4. The LookupError is a base class for all errors that occur when a key or index is not found in a collection or sequence. It is a subclass of the Exception class, and therefore, it is a superclass for more specific error classes.\n",
        "\n",
        "Here are two examples of errors that are defined in subclasses of the LookupError class:\n",
        "\n",
        "1.KeyError: This error occurs when a key is not found in a dictionary. It is a subclass of the LookupError\n",
        "\n",
        "2.IndexError: This error occurs when an index is out of range for a sequence. It is a subclass of the LookupError\n"
      ],
      "metadata": {
        "id": "awAEdSlAushQ"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# Here is an example of code that generates a KeyError:\n",
        "my_dict = {\"apple\": 2, \"banana\": 4, \"orange\": 1}\n",
        "count = my_dict[\"grape\"]   # This will raise a KeyError\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 200
        },
        "id": "9qvYbkfEvv-b",
        "outputId": "2186a40e-4b6b-422a-c6da-138f48bd0b31"
      },
      "execution_count": 6,
      "outputs": [
        {
          "output_type": "error",
          "ename": "KeyError",
          "evalue": "ignored",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
            "\u001b[0;32m<ipython-input-6-8ab41fee24b7>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# Here is an example of code that generates a KeyError:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0mmy_dict\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0;34m\"apple\"\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;36m2\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"banana\"\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;36m4\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"orange\"\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0mcount\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmy_dict\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"grape\"\u001b[0m\u001b[0;34m]\u001b[0m   \u001b[0;31m# This will raise a KeyError\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
            "\u001b[0;31mKeyError\u001b[0m: 'grape'"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#  Here is an example of code that generates an IndexError:\n",
        "my_list = [1, 2, 3, 4, 5]\n",
        "value = my_list[10]  # This will raise an IndexError\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 200
        },
        "id": "RGAQaTCCv2xr",
        "outputId": "3b2df51b-b818-48db-ca77-31d458156f95"
      },
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "error",
          "ename": "IndexError",
          "evalue": "ignored",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)",
            "\u001b[0;32m<ipython-input-5-cfc6bf3171c6>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m#  Here is an example of code that generates an IndexError:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0mmy_list\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m2\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m3\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m4\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m5\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0mvalue\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmy_list\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m10\u001b[0m\u001b[0;34m]\u001b[0m  \u001b[0;31m# This will raise an IndexError\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
            "\u001b[0;31mIndexError\u001b[0m: list index out of range"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "6Ezyyc3Av8Lv"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "Q5. Explain ImportError. What is ModuleNotFoundError?\n",
        "\n",
        "Ans5. ImportError is a Python exception that is raised when a module or a part of a module cannot be imported. This can happen when a required module is missing or when the Python interpreter cannot find the module. The ImportError class is a subclass of the Exception class.\n",
        "\n",
        "In Python 3.6 and later, ModuleNotFoundError is a subclass of the ImportError class. It is a more specific type of ImportError that is raised when a module is not found.\n",
        "\n"
      ],
      "metadata": {
        "id": "zS9FMXl4wEYi"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "import numpy\n",
        "\n",
        "# If numpy is not installed, you will get an ImportError\n"
      ],
      "metadata": {
        "id": "JhW9cxMGwdBK"
      },
      "execution_count": 7,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import my_nonexistent_module\n",
        "\n",
        "# If my_nonexistent_module does not exist, you will get a ModuleNotFoundError\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 339
        },
        "id": "0631w2owwfCS",
        "outputId": "f6f5f935-f79c-4501-d0c9-1c0d3a3717cf"
      },
      "execution_count": 8,
      "outputs": [
        {
          "output_type": "error",
          "ename": "ModuleNotFoundError",
          "evalue": "ignored",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
            "\u001b[0;32m<ipython-input-8-3a6e50b1a9ef>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mmy_nonexistent_module\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;31m# If my_nonexistent_module does not exist, you will get a ModuleNotFoundError\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'my_nonexistent_module'",
            "",
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0;32m\nNOTE: If your import is failing due to a missing package, you can\nmanually install dependencies using either !pip or !apt.\n\nTo view examples of installing some common dependencies, click the\n\"Open Examples\" button below.\n\u001b[0;31m---------------------------------------------------------------------------\u001b[0m\n"
          ],
          "errorDetails": {
            "actions": [
              {
                "action": "open_url",
                "actionText": "Open Examples",
                "url": "/notebooks/snippets/importing_libraries.ipynb"
              }
            ]
          }
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "IeNszNHowkq9"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "Q6. List down some best practices for exception handling in python.\n",
        "\n",
        "Ans6. Here are some best practices for exception handling in Python:\n",
        "\n",
        "1.Catch only the exceptions you can handle: It's generally best to catch specific exceptions that you can handle, rather than catching all exceptions. Catching too many exceptions can make your code harder to debug and can hide important errors.\n",
        "\n",
        "2.Use try/except blocks sparingly: Try to keep the amount of code within try/except blocks to a minimum. This makes it easier to locate and fix errors.\n",
        "\n",
        "3.Keep the try block as small as possible: It is best to keep the try block as small as possible, so that you can pinpoint the exact line of code that caused the error.\n",
        "\n",
        "4.Use the finally block to release resources: If you are using external resources (like files or network connections) in your try block, use the finally block to release them, regardless of whether the try block succeeded or not.\n",
        "\n",
        "\n",
        "5.Don't ignore exceptions: Ignoring exceptions is never a good practice. At the very least, you should log the exception so that you can investigate the problem later.\n",
        "\n",
        "6.Use Python's built-in exceptions whenever possible: Python has many built-in exceptions that cover a wide range of errors. Whenever possible, use these exceptions rather than creating your own custom exceptions.\n"
      ],
      "metadata": {
        "id": "TzLNUsSlwueK"
      }
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "MRbZc09-xTbg"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}